### ISSUE TITLE
Fine-grained control over which points can be unfiltered

### ISSUE THREAD

**Issue by NOT-HAL9000** [flekschas/regl-scatterplot#111]
I'm wondering if it's possible to extend the unfilter method to have more fine grained control over which points get unfiltered. I am trying to implement a "hide" feature and it would be easier for me if I could maintain a permanent list of points to keep filtered. 

This means I can still use filter and unfilter whilst maintaining a list of hidden (that don't get unfiltered).

For example:

```javascript
const points = [ ... ] 
scatterplot.filter(points)
```
This would unfilter the specified points only if they are currently filtered. Do nothing otherwise.
```javascript
scatterplot.unfilter([ ... point idx's to unfilter ... ])
```
This would unfilter all points that have been filtered except for the ones specified. 
```javascript
scatterplot.unfilter({
    allExcept: [ ... point idx's to keep filtered ... ]
}) 

```

It's possible to make this a non-breaking change with detection on input type of unfilter.

**Comment by flekschas** [comment]
It's certainly possible to implement this but I consider this to be a feature of the application that's using `regl-scatterplot` rather than a feature of `regl-scatterplot` itself. 

The good news is that I believe it's fairly simple to implement this with the existing feature set of `regl-scatterplot`. For example, say we have rendered 10 points, and then filter down to 5 as follows:

```js
const filteredPointIdxs = new Set([1, 2, 3, 4, 5]);
scatterplot.filter(Array.from(filteredPointIdxs));
```

If you now want to hide additional points, simple remove them from `filteredPointIdxs` and re-apply the filter:

```js
const hide = (pointIdxs) => {
  pointIdxs.forEach((pointIdx) => filteredPointIdxs.remove(pointIdx));
  scatterplot.filter(Array.from(filteredPointIdxs));
}

hide([3, 4]);
```

The "hide all points except" is the same operation as doing filtering down to the "excepted" points. E.g.:

```js
const hideAllExcept = (pointIdxs) => {
  filteredPointIdxs = new Set(pointIdxs);
  scatterplot.filter(Array.from(filteredPointIdxs));
}
```

Is this what you had in mind?

I don't think there's a need for this to be part of `regl-scatterplot` directly as it seems to be an application-specific use case and straight-forward enough to implement. Let me know if I am missing anything.

**Comment by NOT-HAL9000** [comment]
That makes a lot of sense. Thanks!

I had wrongly assumed that regl-scatterplot has an internal memory where all consecutive calls to ```filter``` would grow the list of already filtered points.

But what you're saying is that every call to ```filter``` replaces the old filtered points with the new filtered points?

**Comment by flekschas** [comment]
> But what you're saying is that every call to filter replaces the old filtered points with the new filtered points?

Correct, there isn't any history involved. When you first call `scatterplot.filter([1,2,3])` and then call `scatterplot.filter([4,5,6])` you would only see points with the index 4, 5, and 6.

**Comment by NOT-HAL9000** [comment]
Perfect, that works for me! Thank you!
