### ISSUE TITLE
Feature: persistent lasso visualisation.

### ISSUE THREAD

**Issue by plankter** [flekschas/regl-scatterplot#19]
Having an option to keep lasso tool displayed after mouse button released is useful when one wants to select regions of interest on background image for further analysis. This will require also introduction of a method to get lasso polygon coordinates, i suppose. Something similar to what OpenLayers is allowing to do:

![Screenshot from 2020-06-04 12-45-12](https://user-images.githubusercontent.com/1336618/83747715-52d5c000-a661-11ea-8418-67d7d28b95bc.png)

**Comment by flekschas** [comment]
Can you elaborate a little bit? For instance, what exactly does OpenLayers allow you to do? How is that implemented?

Since selected points are visualized differently, the selection state is persistent. Hence, from the scatterplot's point of view, I don't know what the benefit of knowing the exact lasso trajectory would be. In the screenshot, it makes sense to see the lasso but this is not the scatterplot is it?

Having said that, I can see that it might be handy in certain applications to know the lasso trajectory. Two ideas come to my mind:

1. Publish the lasso polygon (probably in screen coordinates)
2. Add an option to define when the lasso is cleared. Maybe `lassoClearEvent` with `'mouseup'` as the default value and `'select'` as another option. In the latter case, the lasso would stay until  either `select()` or `deselect()` is triggered.

**Comment by plankter** [comment]
Main reason is that sometimes i would like to use your component as a pure image viewer, when no points are displayed, only a background image (like intensities are known via raster image, but no single cell data to display cells centroids as scatterplot points). In this case region selection isn't obvious without lasso persistence.

In OpenLayers viewer that i am using at the moment, it it possible to create a vector layer over a bitmap layer. This layer can be hidden or shown independently of the raster layer: https://openlayers.org/en/latest/examples/draw-freehand.html?q=vector. For each such vector `feature` it is possible to get lasso's polygon coordinates and use these to analyse regions of the image.

**Comment by flekschas** [comment]
I ended up implementing option 2: there's a new property called `lassoClearEvent`, which is set to `lassoEnd` by default (the same behavior as before). The only other currently supported option is `deselect`, which will preserve the lasso until you either start a new selection or you clear the current selection.

The layering approach makes a lot of sense for a general tool like OpenLayers but regl-scatterplot itself shouldn't manage multiple layers. Publishing the lasso coordinates itself would also not be too helpful as the published coordinates change upon pan/zoom, which would require having to synchronize an external SVG layer with the scatterplot's camera position.

I hope the new option is useful. If you are thinking about permanently annotating image data with polygons I think other tools might be more appropriate.

**Comment by flekschas** [comment]
Closing this as `lassoClearEvent` allows persisting the lasso until the selection is either cleared or a new selection is started. Please feel free to reopen if this does not address your issue.
