### ISSUE TITLE
linear scale relationship of axis

### ISSUE THREAD

**Issue by cherepanovic** [flekschas/regl-scatterplot#29]
Hello Fritz,

my question is whether there is the option to set the linear scale relationship of the axis (as the d3 does it with d3.scaleLinear)?

thanks!

**Comment by flekschas** [comment]
Apologies for my belated reply and thanks for bringing this up. Regl-scatterplot is based on dom-2d-camera and uses a 2D transformation matrix. You can manually convert the scaling back to D3 scales using the `camera.view` that is published via `scatterplot.subscribe('view', ({ view }) => { ... }))`.

Since this isn't super straight forward I implemented a hook to make it easier. See https://github.com/flekschas/regl-scatterplot#synchronize-d3-x-and-y-scales-with-the-scatterplot-view for a simple example and https://github.com/flekschas/regl-scatterplot/blob/master/example/axes.js for a full example with d3 axes.

The online demo is available at https://flekschas.github.io/regl-scatterplot/axes.html

Let me know if this is what you're looking for.

**Comment by cherepanovic** [comment]
is on my to-do list, I appreciate your answers and advices!

**Comment by flekschas** [comment]
I am closing this issue as it appears to have solved the issue. Please reopen if you were looking into something else.
