### ISSUE TITLE
Expose lassoPolygon (lassoPos) data in select event

### ISSUE THREAD

**Issue by plankter** [flekschas/regl-scatterplot#32]
Could you please add information about lasso selection coordinates to the payload of select event in addition to selected points indices? This is useful in case of mapping selected region to a background image.

Thank you for the very nice component.

**Comment by flekschas** [comment]
Thanks for the suggestion. Could you give me an example of what kind of payload you're looking for? Would it be something like a list of tuples describing the extent of the lasso? If so, I could add this. However, it might make sense to introduce a new event type for this (maybe `lasso-end`) because the `select` can also be triggered without lasso coordinates. What do you think?

**Comment by plankter** [comment]
Yes, this is exactly what I am looking for. You are right, `lasso-end` makes more sense.

**Comment by flekschas** [comment]
Hey Anton, I just published a [new version](https://github.com/flekschas/regl-scatterplot/blob/master/CHANGELOG.md#v0140) that should fulfill your requirements. Events are also [documented in more detail now](https://github.com/flekschas/regl-scatterplot#events).

When you update, make sure to check if the breaking changes listed in the change log affect you.

**Comment by plankter** [comment]
Thanks a lot! I'll try it later today.
