### ISSUE TITLE
Wondering how to get it to work when the canvas element does not already exist?

### ISSUE THREAD

**Issue by armsp** [flekschas/regl-scatterplot#81]
This may not be a bug at all...and I am just very new to react.
I have been trying to use your library to show some UMAP projected vectors at a certain position in my webpage. However, everytime I get the error that canvas is null.
I tried searching around and mixed and matched a few things but couldn't get it to work. Its been 2 days and I think I need help.
I have the following code right now -
```jsx
import createScatterplot from 'regl-scatterplot';
import React, { useRef, useEffect } from 'react'

const PreLabeledDocVectors = props => {
    const canvasRef = useRef(null);
    // const { width, height } = canvas.getBoundingClientRect();

    const points = new Array(100)
    .fill()
    .map(() => [-1 + Math.random() * 2, -1 + Math.random() * 2, "#efefef"]);
    const canvas = canvasRef.current;
    const context = canvas.getContext('2d');
    const scatterplot = createScatterplot({
        canvasRef,
        width: 20,
        height: 20,
        pointSize: 5,
      });
  useEffect((points, scatterplot) => {
    canvasRef.current.getCanvas()._canvas.id = 'some-id';
    scatterplot.draw(points);
  }, [scatterplot.draw])

  // scatterplot.draw(points);

    return (
        <div>
            pre labeled doc vectors scatter plot using reactgl scatter
            <canvas ref={canvasRef}/>
        </div>
    );
}

export default PreLabeledDocVectors;
```
Any idea how to get it to work when someone wants to use your library to show a scatterplot inside a certain component amongst many

**Comment by flekschas** [comment]
The following code does not work because `canvasRef` is not a valid property.

```js
createScatterplot({
  canvasRef,
  width: 20,
  height: 20,
  pointSize: 5,
});
```

See https://github.com/flekschas/regl-scatterplot#basic-example, you need to pass the actual canvas element to regl-scatterplot as the `canvas` property. Not a React ref object.

The following should work, however, make sure that `canvasRef.current` is truly a canvas element and not `null`!

```js
createScatterplot({
  canvas: canvasRef.current,
  width: 20,
  height: 20,
  pointSize: 5,
});
```

I personally would probably rather do something like this:

```js
const Component = ({ points }) => {
  const scatterplot = useRef();
  const refHandler = (canvas) => {
    if (!canvas) return;
    scatterplot.current = createScatterplot({
      canvas,
      width: 20,
      height: 20,
      pointSize: 5,
    });
    scatterplot.current.draw(points);
    return () => {
       if (!scatterplot.current) return;
       scatterplot.current.destroy();
       scatterplot.current = undefined;
    }
  }

  useEffect(() => {
    if (!scatterplotRef.current) return;
    scatterplotRef.current.draw(points);
  }, [points]);

  return <canvas ref={refHandler} />;
}
```

**Comment by armsp** [comment]
@flekschas it works! Thank you so very much!

**Comment by flekschas** [comment]
Please open a new ticket with a detailed description. The original issue seems to have been fixed.

My hunch is that you're passing a promise to regl-scatterplot instead of the real data. That's not supported. Simply wait until the promise is resolved first before attempting to call `scatterplot.draw()`. But I am just guessing here.
