### ISSUE TITLE
How to use ndarray or npyjs array (with or without conversion) and pass it as points for the scatterplot?

### ISSUE THREAD

**Issue by armsp** [flekschas/regl-scatterplot#83]
I am wondering if it is possible to use [npyjs](https://github.com/aplbrain/npyjs) or [ndarray](https://github.com/scijs/ndarray) array, with or without conversion as data points to plot the scatterplot.

I have a 2D numpy array file `embeddings.npy` file that I read in React and want to plot using regl-scatterplot, however, I can't seem to get it to work.
So far I have the following based on your last input -
```js
import ndarray from "ndarray";
import npyjs from "npyjs";
import embeddings from "./2DEmbeddings.npy";
import createScatterplot from 'regl-scatterplot';
import React, { useRef, useState, useEffect } from 'react'

const NP = function(){
    const [points, setPoints] = useState([]);  

    const scatterplotRef = useRef();

    let e = new npyjs();
    var em;
    e.load(embeddings).then(
    res => {
        em = ndarray(res.data, res.shape);
        console.log("actual embedding - ", em.data);
        var p = em.data.map((d) => [d[0],d[1], "#efefef"]);
        setPoints(p);
        console.log("P looks like - ", p);
      });
const refHandler = (canvas) => {
    if (!canvas) return;
    const scatterplot = createScatterplot({
      canvas,
      width: 500,
      height: 500,
      pointSize: 10,
    });
    scatterplot.draw(points);
    scatterplotRef.current = scatterplot;
    return () => {
       scatterplot.destroy();
       scatterplotRef.current = undefined;
    }
  }
  useEffect(() => {
    if (!scatterplotRef.current) return;
    scatterplotRef.current.draw(points);
  }, [points]);
    return <canvas ref={refHandler} />;
}

export default NP;
```

**Comment by flekschas** [comment]
What exactly is the error or how do you know it's not working? Is the screen just empty?

One thing that does not work is `[d[0],d[1], "#efefef"]`. Take a look at the [`scatterplot.draw()`](https://github.com/flekschas/regl-scatterplot#scatterplot.draw), you cannot directly pass in any color information. Everything in regl-scatterplot is data driven.

However, a better approach is probably to pass the data in using the columnar-approach via an object:

```js
scatterplot.draw({ x: [], y: [], ?valueA: [], ?valueB: [], ?line: [], ?lineOrder: [] })
```

(In your case you can ignore all props other than `x` and `y`)

A second issue might be that your data points' x&y positions are not yet normalized to `[-1, 1]` (normalized device coordinates). I realized, this isn't pointed out well yet so I updated the README.md. In case you're wondering why the x/y positions need to be normalized: regl-scatterplot is designed to be a lower-level library, whose primary purpose is speed. As such it expects you to normalize the data upfront, using whatever tools/libraries you like.

Finally, since your data seems to be coming from the Python world, you might want to test https://github.com/flekschas/jupyter-scatter, which is a Jupyter Lab/Notebook widget that allows you to directly visualize your embedding within your notebook. It uses regl-scatterplot under the hood  and supports normalization out of the box.

**Comment by flekschas** [comment]
Unfortunately, I can't give application-specific advice and this seems to be a problem with React and ndarray. So I am going to close this ticket for now. But please feel free to reopen it if you run into issues with regl-scatterplot.

My advice would be to look at the data that you're passing to `scatterplotRef.current.draw(...);`. My guess is that it's just a simple array. However, it either needs to be an array of arrays or an object of arrays.

E.g.:

```js
[
  [x1, y1, ...], // 1. point 
  [x2, y2, ...], // 2. point 
  [x3, y3, ...], // 2. point 
  ...
]
``` 

or 

```js
{
  x: [x1, x2, x3, ...],
  y: [y1, y2, y3, ...]
}
```

How you get your data into that format is up to you. I personally would use [Apache Arrow](https://arrow.apache.org/) (with the [IPC format](https://arrow.apache.org/docs/python/ipc.html)) (plus [Arquero](https://github.com/uwdata/arquero)). See https://github.com/flekschas/regl-scatterplot/blob/master/example/multiple-instances.js#L272 for an example. But maybe you can use ndarray's [pick function](https://github.com/scijs/ndarray#arraypickp0-p1-) to extract just the x and y component of your numpy array.
